"""Train an XGBoost model using features generated by feature_extraction.py.

This script expects an Excel file produced by feature_extraction.main().
"""
from __future__ import annotations

import argparse
import os
from typing import Dict, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

IDENTIFIER_COLUMN = "Domain User Form"
LABEL_COLUMN = "Phishing/Suspected Domains (i.e. Class Label)"
MODEL_FEATURE_COLUMNS = [
    "url_length",
    "domain_length",
    "path_length",
    "num_subdomains",
    "num_dots",
    "domain_num_hyphens",
    "num_special_chars",
    "url_entropy",
    "is_idn",
    "brand_word_present",
    "misleading_keyword_present",
    "domain_age_days",
    "Is_Tunneling",
    "ttl_avg",
    "ssim_score",
    "favicon_similarity_score",
    "asn_number",
    "reverse_dns_entropy",
    "typosquatting_score_encoded",
    "brand_position_root_domain",
    "brand_position_subdomain",
    "HTTPS_Yes",
    "domain_exists",
]
DEFAULT_INPUT_PATH = "training_set.xlsx"
DEFAULT_MODEL_OUTPUT = "xgboost_phishing_model.pkl"


def _validate_required_columns(df: pd.DataFrame) -> None:
    missing = {
        IDENTIFIER_COLUMN,
        LABEL_COLUMN,
        *MODEL_FEATURE_COLUMNS,
    } - set(df.columns)
    if missing:
        raise ValueError(
            "Dataset is missing required columns: " + ", ".join(sorted(missing))
        )


def _prepare_features(df: pd.DataFrame) -> pd.DataFrame:
    features = df[MODEL_FEATURE_COLUMNS].copy()
    features = features.apply(pd.to_numeric, errors="coerce")
    features = features.fillna(features.median(numeric_only=True))
    features = features.fillna(0.0)
    return features.astype(np.float32)


def _prepare_labels(df: pd.DataFrame) -> Tuple[np.ndarray, Dict[int, str]]:
    label_series = df[LABEL_COLUMN].astype("category")
    codes = label_series.cat.codes.to_numpy()
    mapping = dict(enumerate(label_series.cat.categories))
    return codes, mapping


def load_dataset(path: str) -> pd.DataFrame:
    df = pd.read_excel(path)
    _validate_required_columns(df)
    df = df.dropna(subset=[LABEL_COLUMN])
    return df


def split_dataset(
    features: pd.DataFrame,
    labels: np.ndarray,
    test_size: float,
    random_state: int,
) -> Tuple[pd.DataFrame, pd.DataFrame, np.ndarray, np.ndarray]:
    unique_classes = np.unique(labels)
    if unique_classes.size < 2:
        raise ValueError(
            "The dataset must contain at least two distinct classes to train a model."
        )
    stratify = labels if unique_classes.size > 1 else None
    try:
        return train_test_split(
            features,
            labels,
            test_size=test_size,
            random_state=random_state,
            stratify=stratify,
        )
    except ValueError:
        # Fallback without stratification for edge cases (very small datasets)
        return train_test_split(
            features,
            labels,
            test_size=test_size,
            random_state=random_state,
            stratify=None,
        )


def train_model(
    X_train: pd.DataFrame,
    y_train: np.ndarray,
    class_count: int,
    random_state: int,
) -> XGBClassifier:
    params = {
        "n_estimators": 400,
        "learning_rate": 0.05,
        "max_depth": 6,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "n_jobs": -1,
        "random_state": random_state,
        # Add class balancing to fix false positive issue
        "scale_pos_weight": 1.0,  # Balance positive/negative classes
        "class_weight": "balanced",  # Automatic class balancing
    }
    if class_count == 2:
        params["objective"] = "binary:logistic"
        params["eval_metric"] = "logloss"
        # For binary classification, add more aggressive regularization
        params["min_child_weight"] = 1.0  # Penalize false positives
        params["gamma"] = 0.1  # Minimum loss reduction for split
    else:
        params["objective"] = "multi:softprob"
        params["eval_metric"] = "mlogloss"
        params["num_class"] = class_count
    model = XGBClassifier(**params)
    model.fit(X_train, y_train)
    return model


def evaluate_model(
    model: XGBClassifier,
    X_test: pd.DataFrame,
    y_test: np.ndarray,
    label_mapping: Dict[int, str],
) -> None:
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    class_names = [str(label_mapping[idx]) for idx in sorted(label_mapping)]
    print("\nModel evaluation")
    print("================")
    print(f"Accuracy: {accuracy:.4f}")
    print("\nClassification report:")
    print(
        classification_report(
            y_test,
            predictions,
            target_names=class_names,
            zero_division=0,
        )
    )
    print("Confusion matrix:")
    print(confusion_matrix(y_test, predictions))


def save_model(
    model: XGBClassifier,
    label_mapping: Dict[int, str],
    feature_columns: Tuple[str, ...],
    output_path: str,
) -> None:
    payload = {
        "model": model,
        "label_mapping": label_mapping,
        "feature_columns": feature_columns,
    }
    directory = os.path.dirname(output_path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    joblib.dump(payload, output_path)
    print(f"\nModel saved to: {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train an XGBoost classifier on extracted phishing URL features.",
    )
    parser.add_argument(
        "--input-excel",
        default=DEFAULT_INPUT_PATH,
        help="Path to the Excel file generated by feature_extraction.py",
    )
    parser.add_argument(
        "--model-output",
        default=DEFAULT_MODEL_OUTPUT,
        help="Destination path for the trained model artifact (.joblib)",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.2,
        help="Fraction of the dataset to reserve for evaluation",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for train/test split and model training",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print("Loading dataset...")
    dataset = load_dataset(args.input_excel)
    features = _prepare_features(dataset)
    labels, label_mapping = _prepare_labels(dataset.loc[features.index])
    print("Splitting dataset...")
    X_train, X_test, y_train, y_test = split_dataset(
        features,
        labels,
        test_size=args.test_size,
        random_state=args.random_state,
    )
    print(f"Training samples: {len(X_train)}, Evaluation samples: {len(X_test)}")
    print("Training XGBoost model...")
    model = train_model(X_train, y_train, class_count=len(label_mapping), random_state=args.random_state)
    evaluate_model(model, X_test, y_test, label_mapping)
    save_model(
        model,
        label_mapping,
        tuple(MODEL_FEATURE_COLUMNS),
        args.model_output,
    )


if __name__ == "__main__":
    main()

